spring:
  application:
    name: ExampleApp
  profiles:
    active: local
qiye:
  wechat:
    corp-id: wwdfd3d5092c21f7fa
    feign-config:
      read-timeout: 6000
      logger-type: slf4j
    apps:
      - app-id: 1000002
        agent-id: 1000002
        secret: nqAGs4dshSX6VviTMvwgrsv0EQHtF5YyWsjolmX5wY0
      - app-id: contact
        agent-id: 88
        app-type: contact
        secret: Zk_wILS77ZbRR05K6vMWJ3GeHR9HSgFY9cXETF6yCmk
